// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_illawarra_plum = "CgkI1MSeptocEAIQCg"; // <GPGSID>
        public const string achievement_durian = "CgkI1MSeptocEAIQBQ"; // <GPGSID>
        public const string achievement_jalapeno = "CgkI1MSeptocEAIQCw"; // <GPGSID>
        public const string leaderboard_timer_level_10 = "CgkI1MSeptocEAIQGQ"; // <GPGSID>
        public const string achievement_grape = "CgkI1MSeptocEAIQCA"; // <GPGSID>
        public const string achievement_cherry = "CgkI1MSeptocEAIQAw"; // <GPGSID>
        public const string achievement_banana = "CgkI1MSeptocEAIQAg"; // <GPGSID>
        public const string leaderboard_timer_level_13 = "CgkI1MSeptocEAIQHA"; // <GPGSID>
        public const string achievement_mango = "CgkI1MSeptocEAIQDg"; // <GPGSID>
        public const string achievement_orange = "CgkI1MSeptocEAIQEA"; // <GPGSID>
        public const string leaderboard_timer_level_11 = "CgkI1MSeptocEAIQGg"; // <GPGSID>
        public const string achievement_apple = "CgkI1MSeptocEAIQAQ"; // <GPGSID>
        public const string achievement_honeydew = "CgkI1MSeptocEAIQCQ"; // <GPGSID>
        public const string achievement_eggplant = "CgkI1MSeptocEAIQBg"; // <GPGSID>
        public const string leaderboard_timer_level_15 = "CgkI1MSeptocEAIQHg"; // <GPGSID>
        public const string leaderboard_timer_level_14 = "CgkI1MSeptocEAIQHQ"; // <GPGSID>
        public const string leaderboard_timer_level_12 = "CgkI1MSeptocEAIQGw"; // <GPGSID>
        public const string achievement_fig = "CgkI1MSeptocEAIQBw"; // <GPGSID>
        public const string achievement_lemon = "CgkI1MSeptocEAIQDQ"; // <GPGSID>
        public const string leaderboard_timer_level_8 = "CgkI1MSeptocEAIQJg"; // <GPGSID>
        public const string achievement_kiwi = "CgkI1MSeptocEAIQDA"; // <GPGSID>
        public const string leaderboard_timer_level_9 = "CgkI1MSeptocEAIQJw"; // <GPGSID>
        public const string leaderboard_timer_level_6 = "CgkI1MSeptocEAIQJA"; // <GPGSID>
        public const string leaderboard_timer_level_1 = "CgkI1MSeptocEAIQHw"; // <GPGSID>
        public const string leaderboard_timer_level_2 = "CgkI1MSeptocEAIQIA"; // <GPGSID>
        public const string leaderboard_timer_level_3 = "CgkI1MSeptocEAIQIQ"; // <GPGSID>
        public const string leaderboard_timer_level_4 = "CgkI1MSeptocEAIQIg"; // <GPGSID>
        public const string leaderboard_timer_level_5 = "CgkI1MSeptocEAIQIw"; // <GPGSID>
        public const string achievement_nectarine = "CgkI1MSeptocEAIQDw"; // <GPGSID>
        public const string leaderboard_timer_level_7 = "CgkI1MSeptocEAIQJQ"; // <GPGSID>

}

