// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_illawarra_plum = "CgkI8suSv-wKEAIQCQ"; // <GPGSID>
        public const string achievement_durian = "CgkI8suSv-wKEAIQBA"; // <GPGSID>
        public const string achievement_jalapeno = "CgkI8suSv-wKEAIQCg"; // <GPGSID>
        public const string leaderboard_timer_level_10 = "CgkI8suSv-wKEAIQGQ"; // <GPGSID>
        public const string achievement_grape = "CgkI8suSv-wKEAIQBw"; // <GPGSID>
        public const string achievement_cherry = "CgkI8suSv-wKEAIQAw"; // <GPGSID>
        public const string achievement_banana = "CgkI8suSv-wKEAIQAg"; // <GPGSID>
        public const string leaderboard_timer_level_13 = "CgkI8suSv-wKEAIQHA"; // <GPGSID>
        public const string achievement_mango = "CgkI8suSv-wKEAIQDQ"; // <GPGSID>
        public const string achievement_orange = "CgkI8suSv-wKEAIQDw"; // <GPGSID>
        public const string leaderboard_timer_level_11 = "CgkI8suSv-wKEAIQGg"; // <GPGSID>
        public const string achievement_apple = "CgkI8suSv-wKEAIQAQ"; // <GPGSID>
        public const string achievement_honeydew = "CgkI8suSv-wKEAIQCA"; // <GPGSID>
        public const string achievement_eggplant = "CgkI8suSv-wKEAIQBQ"; // <GPGSID>
        public const string leaderboard_timer_level_15 = "CgkI8suSv-wKEAIQHg"; // <GPGSID>
        public const string leaderboard_timer_level_14 = "CgkI8suSv-wKEAIQHQ"; // <GPGSID>
        public const string leaderboard_timer_level_12 = "CgkI8suSv-wKEAIQGw"; // <GPGSID>
        public const string achievement_fig = "CgkI8suSv-wKEAIQBg"; // <GPGSID>
        public const string achievement_lemon = "CgkI8suSv-wKEAIQDA"; // <GPGSID>
        public const string leaderboard_timer_level_8 = "CgkI8suSv-wKEAIQFw"; // <GPGSID>
        public const string achievement_kiwi = "CgkI8suSv-wKEAIQCw"; // <GPGSID>
        public const string leaderboard_timer_level_9 = "CgkI8suSv-wKEAIQGA"; // <GPGSID>
        public const string leaderboard_timer_level_6 = "CgkI8suSv-wKEAIQFQ"; // <GPGSID>
        public const string leaderboard_timer_level_1 = "CgkI8suSv-wKEAIQEA"; // <GPGSID>
        public const string leaderboard_timer_level_2 = "CgkI8suSv-wKEAIQEQ"; // <GPGSID>
        public const string leaderboard_timer_level_3 = "CgkI8suSv-wKEAIQEg"; // <GPGSID>
        public const string leaderboard_timer_level_4 = "CgkI8suSv-wKEAIQEw"; // <GPGSID>
        public const string leaderboard_timer_level_5 = "CgkI8suSv-wKEAIQFA"; // <GPGSID>
        public const string achievement_nectarine = "CgkI8suSv-wKEAIQDg"; // <GPGSID>
        public const string leaderboard_timer_level_7 = "CgkI8suSv-wKEAIQFg"; // <GPGSID>

}

