// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_mango = "CgkI1MSeptocEAIQDg"; // <GPGSID>
        public const string leaderboard_time = "CgkI1MSeptocEAIQBA"; // <GPGSID>
        public const string achievement_durian = "CgkI1MSeptocEAIQBQ"; // <GPGSID>
        public const string achievement_lemon = "CgkI1MSeptocEAIQDQ"; // <GPGSID>
        public const string achievement_honeydew = "CgkI1MSeptocEAIQCQ"; // <GPGSID>
        public const string achievement_cherry = "CgkI1MSeptocEAIQAw"; // <GPGSID>
        public const string achievement_eggplant = "CgkI1MSeptocEAIQBg"; // <GPGSID>
        public const string achievement_apple = "CgkI1MSeptocEAIQAQ"; // <GPGSID>
        public const string achievement_fig = "CgkI1MSeptocEAIQBw"; // <GPGSID>
        public const string achievement_nectarine = "CgkI1MSeptocEAIQDw"; // <GPGSID>
        public const string achievement_banana = "CgkI1MSeptocEAIQAg"; // <GPGSID>
        public const string achievement_orange = "CgkI1MSeptocEAIQEA"; // <GPGSID>
        public const string achievement_jalapeno = "CgkI1MSeptocEAIQCw"; // <GPGSID>
        public const string achievement_kiwi = "CgkI1MSeptocEAIQDA"; // <GPGSID>
        public const string achievement_illawarra_plum = "CgkI1MSeptocEAIQCg"; // <GPGSID>
        public const string achievement_grape = "CgkI1MSeptocEAIQCA"; // <GPGSID>

}

